export const TEAM_ACTIONS = {
  ADD_MEMBER: 'ADD_MEMBER',
  CREATE_TEAM: 'CREATE_TEAM',
  DELETE_TEAM: 'DELETE_TEAM',
};

export const PEOPLE_ACTIONS = {
  CREATE_PERSON: 'CREATE_PERSON',
  DELETE_PERSON: 'DELETE_PERSON',
};

export const TABS_ACTIONS = {
  ACTIVE_TAB: 'ACTIVE_TAB',
};
